### ISSUE TITLE
Package structure and command line

### ISSUE THREAD

**Issue by jcarbaugh** [SarahJaine/mo-cli#2]
Instead of _init.py_ taking a single project parameter, the end goal is to have a command like `mo init django`. To do this, init will have to be a subcommand of a primary mo command, instead of being a standalone script.

Check out [a demo franklin cli](https://github.com/jcarbaugh/franklin-cli) as reference.

**Comment by jcarbaugh** [comment]
Also, take a look at the general package naming and structure.

**Comment by SarahJaine** [comment]
Check out my changes on the wo-subprocess branch.  Let me know what you think! :)

**Comment by jcarbaugh** [comment]
Belated 👍  :)
